(function () {
  'use strict';
  const C=globalThis.SettlementCore,data=globalThis.SETTLEMENT_CATALOG,root=document.getElementById('settlement-library');
  if(!root)return;
  const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined&&text!==null)e.textContent=String(text);if(cls)e.className=cls;return e;};
  if(!C||!data||!Array.isArray(data.records)){root.append(el('div','The settlement catalog could not be loaded. Reload this page or open the catalog JSON from the library folder.','sl-error'));return;}
  const records=data.records,byId=new Map(records.map(r=>[r.id,r])),meta=data.metadata,base=root.dataset.libraryBase||'',pageSize=30;
  const state={query:'',category:'',state:'',proof:'',status:'',evidence:'',deadline:'',includeNationwide:true,localOnly:false,collection:'all',sort:'upcoming',asOf:C.localToday(),selected:null,tab:'overview',page:0};
  const controls={},saved=new Set(),compared=new Set();let filtered=[],dialog=null,toastTimer,searchTimer;
  try{const v=JSON.parse(localStorage.getItem('sw:settlement-library:saved:v1')||'[]');if(Array.isArray(v))for(const id of v)if(byId.has(id))saved.add(id);}catch{}
  const button=(text,fn,cls)=>{const b=el('button',text,cls);b.type='button';b.addEventListener('click',fn);return b;};
  const localLink=(text,path)=>{const a=el('a',text);a.href=base+path;return a;};
  const external=(text,url)=>{const u=C.safeURL(url);if(!u)return el('span',typeof url==='string'&&url&&!/^https?:/.test(url)?url:'Link not supplied','sl-muted');const a=el('a',text);a.href=u;a.target='_blank';a.rel='noopener noreferrer';return a;};
  const labelFor=(label,key,tag='input')=>{const l=el('label',label);const f=el(tag);f.id='sl-'+key;f.setAttribute('aria-label',label);l.append(f);controls[key]=f;return l;};
  const option=(value,text)=>{const o=el('option',text);o.value=value;return o;};
  const select=(label,key,values)=>{const l=labelFor(label,key,'select');for(const [v,t]of values)controls[key].append(option(v,t));controls[key].addEventListener('change',()=>{state[key]=controls[key].value;state.page=0;render();});return l;};
  const list=items=>{const u=el('ul');for(const item of items||[])u.append(el('li',item));return u;};
  const dl=items=>{const d=el('dl',null,'sl-facts');for(const [label,value]of items){d.append(el('dt',label),el('dd',value==null||value===''?'Not stated':value));}return d;};
  const section=(parent,title,text)=>{parent.append(el('h3',title));if(typeof text==='string')parent.append(el('p',text));else if(text)parent.append(text);};
  function notify(text){notice.textContent=text;notice.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>notice.hidden=true,4000);}
  function download(text,name,mime='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type:mime})),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function save(id){if(saved.has(id))saved.delete(id);else saved.add(id);try{localStorage.setItem('sw:settlement-library:saved:v1',JSON.stringify([...saved]));}catch{notify('Saved for this visit. Browser storage is unavailable.');}render();}
  function compareToggle(id){if(compared.has(id))compared.delete(id);else if(compared.size<4)compared.add(id);else{notify('Compare up to four settlements at a time.');renderList();return;}renderCompareButton();renderList();}
  const skip=el('a','Skip to settlements');skip.href='#settlement-main';skip.className='sl-skip';skip.addEventListener('click',e=>{e.preventDefault();main.tabIndex=-1;main.focus();main.scrollIntoView();});root.append(skip);
  const header=el('header',null,'sl-header');header.append(el('div','SEEGER WEISS / PRACTICE INTELLIGENCE','sl-eyebrow'));
  const headrow=el('div',null,'sl-headrow'),headtitle=el('div');headtitle.append(el('h1','Settlement intelligence'),el('p','Explore reported benefits, claim requirements, deadlines, and the sources behind each settlement.','sl-subtitle'));headrow.append(headtitle,localLink('Research & agent skills →','SKILLS.html'));header.append(headrow);
  const nav=el('nav');nav.setAttribute('aria-label','Library navigation');for(const [label,path]of [['Documents','index.html'],['Court coverage','COVERAGE.html'],['Rules & procedure','RULES.html'],['Primary law','LAW.html'],['Additional sources','EXTENDED-LAW.html'],['Workflow toolkit','TOOLKIT.html'],['Agent skills','SKILLS.html'],['Platform resources','CORPUS.html']])nav.append(localLink(label,path));const active=el('span','Settlements');active.setAttribute('aria-current','page');nav.append(active);header.append(nav);root.append(header);
  const main=el('main');main.id='settlement-main';const metrics=el('div',null,'sl-metrics');
  const metricNodes={};for(const [key,n,label,note]of [['records',records.length,'Catalog entries','Every supplied record retained'],['dates',records.filter(r=>r.publisher.claim_deadline).length,'Reported claim dates','Cutoff times are not supplied'],['reviews',records.filter(r=>r.review).length,'Source-reviewed references','Dated checks and corrections attached'],['documents',new Set(records.flatMap(r=>(r.review?.documents||[]).filter(d=>d.status==='downloaded'&&d.sha256&&C.localDocument(d.path)).map(d=>d.sha256))).size,'Saved source PDFs','Original notices and claim forms']]){const m=el('div');const line=el('div');metricNodes[key]=el('strong',n);line.append(metricNodes[key],el('span',label));m.append(line,el('p',note));metrics.append(m);}main.append(metrics);
  const infobar=el('div',null,'sl-infobar');infobar.append(el('span','Feed snapshot: '+C.prettyDate(meta.generated?.slice(0,10))+' · Reported fields remain separate from independent source reviews.'));const asof=labelFor('Compare dates as of','asOf');controls.asOf.type='date';controls.asOf.value=state.asOf;controls.asOf.addEventListener('change',()=>{const date=controls.asOf.value;if(C.isoDay(date)===null){controls.asOf.setCustomValidity('Select a valid date.');controls.asOf.reportValidity();notify('Date filters still use '+C.prettyDate(state.asOf)+'.');return;}controls.asOf.setCustomValidity('');state.asOf=date;render();});infobar.append(asof);main.append(infobar);
  const views=el('div',null,'sl-views');views.setAttribute('aria-label','Settlement collection');const viewButtons={};for(const [id,name]of [['all','All settlements'],['upcoming','Next 30 days'],['reviewed','Source reviewed'],['saved','Saved']]){const b=button(name,()=>{state.collection=id;state.page=0;render();});viewButtons[id]=b;views.append(b);}main.append(views);
  const filters=el('section',null,'sl-filters');filters.setAttribute('aria-label','Filter settlements');const searchLabel=labelFor('Search settlements','query');controls.query.type='search';controls.query.placeholder='Company, case, benefit, court, or keyword…';controls.query.autocomplete='off';controls.query.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=controls.query.value;state.page=0;render();},120);});controls.query.addEventListener('keydown',e=>{if(e.key==='Escape'){clearTimeout(searchTimer);state.query='';controls.query.value='';state.page=0;render();}});filters.append(searchLabel);
  const categories=[...new Set(records.map(r=>r.publisher.category||'Uncategorized'))].sort();filters.append(select('Category (feed)','category',[['','All categories'],...categories.map(v=>[v,v])]));
  const stateCodes=['AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','PR','GU','VI','AS','MP'];
  filters.append(select('Class geography (feed)','state',[['','All locations'],['nationwide','Nationwide (feed)'],...stateCodes.map(v=>[v,v])]));
  filters.append(select('Reported claim date','deadline',[['','Any date'],['7','Next 7 days'],['30','Next 30 days'],['90','Next 90 days'],['past','Date has passed'],['missing','Not stated']]));main.append(filters);
  const more=el('details',null,'sl-more');more.append(el('summary','More filters'));const extra=el('div',null,'sl-extra');extra.append(select('Proof required (feed)','proof',[['','Any requirement'],['yes','Yes'],['optional','Optional'],['no','No'],['unknown','Unknown']]));extra.append(select('Claim status (feed)','status',[['','Any status'],...[...new Set(records.map(r=>r.publisher.status))].sort().map(v=>[v,v])]));extra.append(select('Publisher verification tier','evidence',[['','All publisher tiers'],...[...new Set(records.map(r=>r.publisher.verification_status))].sort().map(v=>[v,v.replaceAll('_',' ')])]));
  const checks=el('div',null,'sl-checks');for(const [key,label]of [['includeNationwide','Include nationwide entries in state results'],['localOnly','Has saved source PDFs']]){const l=el('label');const input=el('input');input.type='checkbox';input.checked=state[key];input.addEventListener('change',()=>{state[key]=input.checked;state.page=0;render();});controls[key]=input;l.append(input,document.createTextNode(label));checks.append(l);}extra.append(checks);more.append(extra);main.append(more);
  const toolbar=el('div',null,'sl-toolbar'),count=el('span',null,'sl-count');count.setAttribute('role','status');count.setAttribute('aria-live','polite');toolbar.append(count);const actions=el('div',null,'sl-toolbar-actions');actions.append(select('Sort','sort',[['upcoming','Next reported date'],['title','Title A–Z'],['reviewed','Source reviewed first'],['verified','Publisher check date']]));const compareButton=button('Compare (0)',openComparison);const exportButton=button('Export filtered CSV',()=>{if(!filtered.length)return;download(C.csv(filtered,meta),'settlement-catalog-filtered.csv','text/csv;charset=utf-8');notify(filtered.length+' filtered records exported.');});actions.append(compareButton,exportButton,button('Reset filters',reset));toolbar.append(actions);main.append(toolbar);
  const grid=el('div',null,'sl-grid');const left=el('section',null,'sl-list-panel');left.setAttribute('aria-label','Settlement results');const table=el('table',null,'sl-table');table.append(el('caption','Settlement catalog · reported fields','sl-sr'));const thead=el('thead'),tr=el('tr');for(const t of ['Compare','Settlement','Reported claim date','Save'])tr.append(el('th',t));thead.append(tr);const tbody=el('tbody');table.append(thead,tbody);const tableWrap=el('div',null,'sl-table-wrap');tableWrap.append(table);left.append(tableWrap);const pager=el('div',null,'sl-pager');const previous=button('Previous',()=>{state.page--;renderList();tableWrap.scrollTop=0;});const pageLabel=el('span');const next=button('Next',()=>{state.page++;renderList();tableWrap.scrollTop=0;});pager.append(previous,pageLabel,next);left.append(pager);const inspector=el('article',null,'sl-inspector');inspector.setAttribute('aria-label','Selected settlement');grid.append(left,inspector);main.append(grid);root.append(main);
  const footer=el('footer',null,'sl-footer');footer.append(el('span','Data: '),external('SettleSignal (settlesignal.com)','https://settlesignal.com/'),el('span',' · Used with attribution. Saved entries stay in this browser. No live monitoring or claim submission.'),localLink('Catalog JSON','07-Settlement-References/catalog/catalog.json'),localLink('Integration guide','07-Settlement-References/catalog/README.md'));root.append(footer);
  const notice=el('div',null,'sl-toast');notice.hidden=true;notice.setAttribute('role','status');root.append(notice);
  function reset(){clearTimeout(searchTimer);Object.assign(state,{query:'',category:'',state:'',proof:'',status:'',evidence:'',deadline:'',includeNationwide:true,localOnly:false,collection:'all',sort:'upcoming',page:0});for(const key of ['query','category','state','proof','status','evidence','deadline','sort'])controls[key].value=state[key];controls.includeNationwide.checked=true;controls.localOnly.checked=false;render();}
  function writeHash(){const p=new URLSearchParams();if(state.selected)p.set('settlement',state.selected);if(state.tab!=='overview')p.set('tab',state.tab);for(const key of ['query','category','state','proof','status','evidence','deadline'])if(state[key])p.set(key,state[key]);if(state.collection!=='all')p.set('collection',state.collection);if(state.sort!=='upcoming')p.set('sort',state.sort);if(!state.includeNationwide)p.set('nationwide','0');if(state.localOnly)p.set('pdf','1');p.set('asof',state.asOf);try{history.replaceState(null,'','#'+p.toString());}catch{}}
  function readHash(){clearTimeout(searchTimer);const p=new URLSearchParams(location.hash.slice(1));for(const key of ['query','category','state','proof','status','evidence','deadline']){let v=p.get(key)||'';if(controls[key].tagName==='SELECT'&&![...controls[key].options].some(o=>o.value===v))v='';state[key]=v;controls[key].value=v;}state.collection=['all','upcoming','reviewed','saved'].includes(p.get('collection'))?p.get('collection'):'all';state.sort=['upcoming','title','reviewed','verified'].includes(p.get('sort'))?p.get('sort'):'upcoming';controls.sort.value=state.sort;state.asOf=C.isoDay(p.get('asof'))!==null?p.get('asof'):C.localToday();controls.asOf.value=state.asOf;controls.asOf.setCustomValidity('');state.includeNationwide=p.get('nationwide')!=='0';controls.includeNationwide.checked=state.includeNationwide;state.localOnly=p.get('pdf')==='1';controls.localOnly.checked=state.localOnly;state.tab=['overview','review','provenance'].includes(p.get('tab'))?p.get('tab'):'overview';let id=p.get('settlement');if(!byId.has(id)){const old=records.find(r=>r.review?.id===id);id=old?.id;}state.selected=byId.has(id)?id:null;state.page=0;render(true);}
  function render(fromHash=false){filtered=C.sortRecords(C.filterRecords(records,state,saved),state.sort,state.asOf);if(!filtered.some(r=>r.id===state.selected)){state.selected=filtered[0]?.id||null;state.tab='overview';}if(fromHash&&state.selected)state.page=Math.floor(filtered.findIndex(r=>r.id===state.selected)/pageSize);state.page=Math.max(0,Math.min(state.page,Math.max(0,Math.ceil(filtered.length/pageSize)-1)));count.textContent=filtered.length+' of '+records.length+' settlements';exportButton.disabled=!filtered.length;for(const [id,b]of Object.entries(viewButtons)){b.setAttribute('aria-pressed',String(state.collection===id));const n=id==='all'?records.length:id==='reviewed'?records.filter(r=>r.review).length:id==='saved'?saved.size:records.filter(r=>{const d=C.daysUntil(r.publisher.claim_deadline,state.asOf);return d!==null&&d>=0&&d<=30;}).length;b.textContent=({all:'All settlements',upcoming:'Next 30 days',reviewed:'Source reviewed',saved:'Saved'})[id]+' ('+n+')';}renderCompareButton();renderList();renderDetail();writeHash();}
  function renderCompareButton(){compareButton.textContent='Compare ('+compared.size+')';compareButton.disabled=compared.size<2;}
  function choose(id){state.selected=id;state.tab='overview';renderList();renderDetail();writeHash();const heading=inspector.querySelector('h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});if(innerWidth<850)inspector.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}}
  function renderList(){tbody.replaceChildren();for(const r of filtered.slice(state.page*pageSize,(state.page+1)*pageSize)){const p=r.publisher,row=el('tr');row.setAttribute('aria-selected',String(r.id===state.selected));const compare=el('td');const checkbox=el('input');checkbox.type='checkbox';checkbox.checked=compared.has(r.id);checkbox.setAttribute('aria-label','Compare '+p.title);checkbox.addEventListener('change',()=>compareToggle(r.id));compare.append(checkbox);const name=el('td'),open=button('',()=>choose(r.id),'sl-open');open.setAttribute('aria-label','Open '+p.title);open.append(el('strong',p.title),el('span',p.category||C.typeLabel(p.settlement_type),'sl-rowmeta'));const tags=el('div',null,'sl-rowtags');tags.append(el('span',p.status));if(r.review)tags.append(el('span','Source review','sl-reviewed'));open.append(tags);name.append(open);const date=el('td',null,'sl-date-cell');date.append(el('strong',C.prettyDate(p.claim_deadline)));const days=C.daysUntil(p.claim_deadline,state.asOf);date.append(el('span',days===null?'No date supplied':days<0?'Reported date passed':days===0?'Today · cutoff unstated':days===1?'In 1 day':'In '+days+' days',days!==null&&days>=0&&days<=7?'sl-date-near':''));const bookmark=el('td');const b=button(saved.has(r.id)?'★':'☆',()=>save(r.id),'sl-bookmark');b.setAttribute('aria-label',(saved.has(r.id)?'Unsave ':'Save ')+p.title);b.setAttribute('aria-pressed',String(saved.has(r.id)));bookmark.append(b);row.append(compare,name,date,bookmark);tbody.append(row);}if(!filtered.length){const row=el('tr'),cell=el('td');cell.colSpan=4;cell.className='sl-empty';cell.append(el('strong',state.collection==='saved'?'No saved settlements match':'No matching settlements'),el('p','Try a broader search or reset the filters.'),button('Reset filters',reset));row.append(cell);tbody.append(row);}pageLabel.textContent=(filtered.length?state.page+1:0)+' / '+Math.ceil(filtered.length/pageSize);previous.disabled=state.page===0;next.disabled=(state.page+1)*pageSize>=filtered.length;}
  function renderDetail(){inspector.replaceChildren();const r=byId.get(state.selected);if(!r){inspector.append(el('p','Choose a settlement to view its benefits, requirements and sources.','sl-empty'));return;}const p=r.publisher,v=r.review;const head=el('div',null,'sl-detail-head');head.append(el('div',C.typeLabel(p.settlement_type),'sl-eyebrow'),el('h2',p.title));const tools=el('div',null,'sl-detail-actions');const bookmark=button(saved.has(r.id)?'Saved':'Save',()=>save(r.id));bookmark.setAttribute('aria-pressed',String(saved.has(r.id)));tools.append(bookmark,button('Research brief',()=>{download(C.researchBrief(r,meta),r.id+'-research-brief.md','text/markdown;charset=utf-8');notify('Research brief downloaded.');},'sl-primary'),button('JSON',()=>{download(JSON.stringify({metadata:meta,record:C.exportRecord(r)},null,2),r.id+'.json','application/json');notify('Settlement record exported.');}));head.append(tools);inspector.append(head);
    const tabs=el('div',null,'sl-detail-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Settlement details');const tabList=[['overview','Overview'],['review','Source review'+(v?'':' (none)')],['provenance','Provenance']];for(const [i,[id,name]]of tabList.entries()){const b=button(name,()=>{state.tab=id;renderDetail();writeHash();inspector.querySelector('[aria-selected=true]').focus();});b.id='sl-tab-'+id;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(state.tab===id));b.setAttribute('aria-controls','sl-detail-content');b.tabIndex=state.tab===id?0:-1;b.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const index=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;state.tab=tabList[index][0];renderDetail();writeHash();inspector.querySelector('[aria-selected=true]').focus();}});tabs.append(b);}inspector.append(tabs);const body=el('div',null,'sl-detail-content');body.id='sl-detail-content';body.tabIndex=0;body.setAttribute('role','tabpanel');body.setAttribute('aria-labelledby','sl-tab-'+state.tab);
    if(state.tab==='overview'){
      if(v){const note=el('div',null,'sl-callout');note.append(el('strong','Source review attached · '+C.prettyDate(v.assessment_date)),el('p',v.status),button('Read the source review',()=>{state.tab='review';renderDetail();writeHash();}));body.append(note);}
      body.append(dl([['Reported claim date',C.prettyDate(p.claim_deadline)],['Status in feed',p.status],['Proof in feed',p.proof_required==='no'?'No (feed shorthand; eligibility may still require attestation)':p.proof_required],['Geography in feed',C.reportedGeography(r)]]));
      body.append(el('p','Geography describes the feed’s state restriction field, not the full class definition or court jurisdiction.','sl-helper'));
      section(body,'Benefits as reported',p.estimated_payout||'No benefit description was supplied in the feed.');body.append(el('p','Source text may describe a total fund, a maximum reimbursement, an estimated award, or noncash benefits. It is not a normalized per-person payout.','sl-helper'));
      const notes=C.flags(r,state.asOf);if(notes.length){const d=el('details');d.append(el('summary','Data notes ('+notes.length+')'),list(notes));body.append(d);}
      section(body,'Source links');const links=el('div',null,'sl-source-links');links.append(external('Settlement site (feed) ↗',p.official_settlement_url),external('Claim form / portal (feed) ↗',p.official_claim_url),external('Publisher record ↗',p.url));body.append(links,el('p','Links open the supplied websites. A link alone does not confirm a current claim window or individual eligibility.','sl-helper'));
      section(body,'Use in research');body.append(localLink('Settlement evidence and comparison agent →','SKILLS.html#skill=sw-settlement-valuation-analyst'),el('p','Generate a scoped research brief, then use the host platform to obtain current evidence.','sl-helper'));
    }else if(state.tab==='review'){
      if(!v){body.append(el('h3','No independent review attached'),el('p','This record is available as attributed source data. The publisher’s tier is “'+p.verification_status.replaceAll('_',' ')+'”; it is not a review performed by this library.'),el('p','Use the research brief to check current notices, class eligibility, benefit options and operative dates before relying on them.'));}
      else{body.append(el('div','Selected fields checked against official public sources on '+C.prettyDate(v.assessment_date)+'.','sl-callout'),el('h3',v.title),el('p',v.summary),dl([['Court',v.court],['Case number',v.case_number],['Jurisdiction',v.jurisdiction],['Claim required at review',v.claim_required===false?'No affirmative claim required':v.claim_required===true?'Yes':'Not determined'],['Reviewed claim date',C.prettyDate(v.claim_deadline)],['Reviewed process',v.status]]));section(body,'Eligibility scope checked',v.eligibility_scope);section(body,'Proof and qualifications',v.proof_requirement);
       if(v.discrepancies?.length){section(body,'Corrections & qualifications');for(const issue of v.discrepancies){const card=el('div',null,'sl-issue');card.append(el('strong',issue.field.replaceAll('_',' ')),el('p',issue.official_observation),el('p',issue.note),external(issue.source_locator||'Supporting source ↗',issue.source_url));body.append(card);}}
       section(body,'Separate event dates');const dates=el('div',null,'sl-event-list');for(const d of v.deadlines||[]){const row=el('div');row.append(el('strong',d.type.replaceAll('_',' ')+' · '+C.prettyDate(d.date)));if(d.time_as_published)row.append(el('p',[d.time_as_published,d.timezone_as_published].filter(Boolean).join(' · ')));if(d.submission_method_or_cutoff)row.append(el('p',d.submission_method_or_cutoff));if(d.uncertainty)row.append(el('p',d.uncertainty));row.append(external(d.source_locator||'Date source ↗',d.source_url));dates.append(row);}body.append(dates);
       if(v.documents?.length){section(body,'Source documents');for(const d of v.documents){const path=C.localDocument(d.path);if(d.status==='downloaded'&&path){const a=localLink(d.title+' · PDF ('+d.page_count+' pages)',path);a.target='_blank';a.rel='noopener';a.className='sl-document';body.append(a);}else{body.append(external(d.title+' ↗',d.url),el('p','Source link; this document is not saved locally.','sl-helper'));}}}
       section(body,'Review coverage',list(v.independent_review.scope));body.append(el('p',v.independent_review.limitations,'sl-helper'));if(v.notes?.length){const notes=el('details');notes.append(el('summary','Review notes'),list(v.notes));body.append(notes);}section(body,'Primary sources');for(const src of v.independent_review.sources||[])body.append(external(src.locator||'Official source ↗',src.url));
      }
    }else{body.append(dl([['Provider','SettleSignal'],['Source row',r.source_positions.join(', ')],['Feed generated',meta.generated],['Provider modified',meta.dateModified],['Publisher last check',p.last_verified],['Publisher tier',p.verification_status],['Publisher evidence flag',String(p.accepted_official_evidence)],['Independent review',v?'Bounded review attached; see its scope':'Not performed by this library']]));body.append(el('p','The evidence flag and tier are preserved as publisher metadata. They do not verify every field or establish a current legal conclusion.','sl-helper'),external('Publisher source ↗',p.url));const details=el('details');details.append(el('summary','Complete original record'),el('pre',JSON.stringify(p,null,2)));body.append(details);const hashes=el('details');hashes.append(el('summary','Record and source fingerprints'),el('pre','ID: '+r.id+'\nSource row SHA-256: '+r.publisher_record_sha256+'\nSnapshot SHA-256: '+r.source_snapshot_sha256));body.append(hashes);section(body,'Attribution and reuse',meta.license);body.append(external('SettleSignal (settlesignal.com)','https://settlesignal.com/'));}
    inspector.append(body);
  }
  function openComparison(){if(compared.size<2)return;if(dialog)dialog.close();const selected=records.filter(r=>compared.has(r.id));dialog=el('dialog',null,'sl-dialog');dialog.setAttribute('aria-label','Compare settlements');const heading=el('div',null,'sl-dialog-head');heading.append(el('h2','Compare settlements'),button('Close',()=>dialog.close()));dialog.append(heading,el('p','Compare reported terms and source coverage. Benefit descriptions are not equivalent valuation measures.','sl-dialog-note'));const wrap=el('div',null,'sl-comparison-wrap'),t=el('table'),head=el('thead'),h=el('tr');h.append(el('th','Field'));for(const r of selected)h.append(el('th',r.publisher.title));head.append(h);t.append(head);const body=el('tbody');for(const [label,get]of [['Reported claim date',r=>C.prettyDate(r.publisher.claim_deadline)],['Feed status',r=>r.publisher.status],['Reviewed process',r=>r.review?.status||'No independent source review'],['Proof (feed)',r=>r.publisher.proof_required],['Geography (feed)',C.reportedGeography],['Benefits as reported',r=>r.publisher.estimated_payout||'Not stated'],['Review corrections',r=>(r.review?.discrepancies||[]).map(d=>d.official_observation).join(' ')||'None attached'],['Publisher record',r=>r.publisher.url]]){const row=el('tr');row.append(el('th',label));for(const r of selected)row.append(el('td',get(r)));body.append(row);}t.append(body);wrap.append(t);dialog.append(wrap);const actions=el('div',null,'sl-dialog-actions');actions.append(button('Export comparison CSV',()=>download(C.csv(selected,meta),'settlement-comparison.csv','text/csv;charset=utf-8')),button('Clear comparison',()=>{compared.clear();dialog.close();renderCompareButton();renderList();}));dialog.append(actions);dialog.addEventListener('close',()=>{dialog.remove();dialog=null;(compareButton.disabled?exportButton:compareButton).focus();});root.append(dialog);dialog.showModal();}
  window.addEventListener('hashchange',readHash);readHash();
})();
